apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-reader
  labels:
    app: logs-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs-reader
  template:
    metadata:
      labels:
        app: logs-reader
    spec:
      serviceAccountName: logs-reader
      containers:
      - name: logs-reader
        image: smvfal/logs-reader:latest
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
            value: "openfaas"