apiVersion: apps/v1
kind: Deployment
metadata:
  name: top
  labels:
    app: top
spec:
  replicas: 1
  selector:
    matchLabels:
      app: top
  template:
    metadata:
      labels:
        app: top
    spec:
      serviceAccountName: top
      containers:
      - name: top
        image: smvfal/top:latest
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
            value: "openfaas"